use cafelatte;

insert into Product (Name, Description, ImageURL, Price, CategoryCode, Stock, Status)
values ('Cappuccino', 'A rich, creamy coffee drink made with steamed milk and foamed milk.',
        'https://upload.wikimedia.org/wikipedia/commons/3/3a/Cappuccino.jpg', 4.50, 'HOTBEV',
        50, 1),
       ('Espresso', 'A strong, concentrated coffee drink made by forcing hot water through finely-ground coffee beans.',
        'https://www.nescafe.com/es/sites/default/files/GettyImages-595948372_desktop.jpg', 3.50, 'HOTBEV', 25,
        1),
       ('Latte', 'A coffee drink made with espresso, steamed milk, and foamed milk.',
        'https://upload.wikimedia.org/wikipedia/commons/f/f9/Caffe_Latte.jpg', 5.00, 'HOTBEV', 100, 1),
       ('Mocha', 'A coffee drink made with espresso, steamed milk, chocolate syrup, and foamed milk.',
        'https://images.immediate.co.uk/production/volatile/sites/2/2021/11/Mocha-1fc71f7.png',
        5.50, 'HOTBEV', 75, 1),
       ('Tea Latte', 'A coffee drink made with tea, steamed milk, and foamed milk.',
        'https://upload.wikimedia.org/wikipedia/commons/f/fb/Chai_Latte_Composition_%2839244770030%29.jpg', 4.50,
        'HOTBEV', 50, 1),
       ('Iced Coffee', 'Coffee that has been brewed hot and then chilled.',
        'https://hips.hearstapps.com/hmg-prod/images/iced-coffee-1597680350.jpg', 4.00, 'COLBEV', 100,
        1),
       ('Iced Tea', 'Tea that has been brewed hot and then chilled.',
        'https://images.pexels.com/photos/792613/pexels-photo-792613.jpeg?cs=srgb&dl=pexels-barbara-webb-792613.jpg&fm=jpg',
        3.50, 'COLBEV', 75, 1),
       ('Smoothie', 'A blended drink made with fruit, yogurt, and other ingredients.',
        'https://upload.wikimedia.org/wikipedia/commons/7/70/Smoothie_de_frutas_naturales.jpg', 5.00, 'COLBEV', 50,
        1),
       ('Frappuccino', 'A blended coffee drink made with ice, milk, coffee, and other ingredients.',
        'https://fotografias.antena3.com/clipping/cmsimages02/2023/05/16/78673B35-650A-452D-933F-C9A7654F0A3D/frappuccino_98.jpg',
        5.50, 'COLBEV', 75, 1),
       ('Chocolate Cake', 'A rich, chocolate cake topped with chocolate frosting.',
        'https://sallysbakingaddiction.com/wp-content/uploads/2013/04/triple-chocolate-cake-4.jpg',
        5.00, 'DESSER',
        25, 1),
       ('Vanilla Cupcake', 'A moist, vanilla cupcake topped with vanilla frosting.',
        'https://hips.hearstapps.com/del.h-cdn.co/assets/18/07/1518475314-vanilla-cupcake-horizontal-.jpg',
        3.50, 'DESSER', 50, 1),
       ('Cheesecake', 'A rich, creamy cheesecake topped with fresh fruit.',
        'https://www.recetasnestle.com.ec/sites/default/files/2022-06/cheesecake-fresas.jpg.jpg',
        6.00, 'DESSER', 100, 1),
       ('Ice Cream Sandwich', 'A chocolate chip cookie with a scoop of vanilla ice cream in the middle.',
        'https://mejoresrecetas.me/wp-content/uploads/2023/04/cheesecake.jpg',
        4.00,
        'DESSER', 75, 1);
