insert into product (Name, Description, ImageURL, Price, CategoryCode, Stock, Status)
values ('Cappuccino', 'A rich, creamy coffee drink made with steamed milk and foamed milk.',
        'https://www.coffeebean.com/content/dam/coffeebean/products/drinks/cappuccino/cappuccino.jpg', 4.50, 'HOTBEV',
        50, 1),
       ('Espresso', 'A strong, concentrated coffee drink made by forcing hot water through finely-ground coffee beans.',
        'https://www.starbucks.com/content/dam/brand/coffee/coffee/espresso/espresso.jpg', 3.50, 'HOTBEV', 25, 1),
       ('Latte', 'A coffee drink made with espresso, steamed milk, and foamed milk.',
        'https://www.nespresso.com/us/en/recipes/latte', 5.00, 'HOTBEV', 100, 1),
       ('Mocha', 'A coffee drink made with espresso, steamed milk, chocolate syrup, and foamed milk.',
        'https://www.starbucks.com/content/dam/brand/coffee/coffee/mocha/mocha.jpg', 5.50, 'HOTBEV', 75, 1),
       ('Tea Latte', 'A coffee drink made with tea, steamed milk, and foamed milk.',
        'https://www.teavana.com/us/en/teas/black-teas/chai-latte-black-tea.html', 4.50, 'HOTBEV', 50, 1),
       ('Iced Coffee', 'Coffee that has been brewed hot and then chilled.',
        'https://www.starbucks.com/content/dam/brand/coffee/coffee/iced-coffee/iced-coffee.jpg', 4.00, 'COLBEV', 100,
        1),
       ('Iced Tea', 'Tea that has been brewed hot and then chilled.',
        'https://www.teavana.com/us/en/teas/black-teas/iced-black-tea.html', 3.50, 'COLBEV', 75, 1),
       ('Smoothie', 'A blended drink made with fruit, yogurt, and other ingredients.',
        'https://www.smoothieking.com/images/smoothies/chocolate-peanut-butter-smoothie-hero.png', 5.00, 'COLBEV', 50,
        1),
       ('Frappuccino', 'A blended coffee drink made with ice, milk, coffee, and other ingredients.',
        'https://www.starbucks.com/content/dam/brand/coffee/coffee/frappuccino/frappuccino.jpg', 5.50, 'COLBEV', 75, 1),
       ('Chocolate Cake', 'A rich, chocolate cake topped with chocolate frosting.',
        'https://www.marthastewart.com/1166685/chocolate-cake', 5.00, 'DESSER', 25, 1),
       ('Vanilla Cupcake', 'A moist, vanilla cupcake topped with vanilla frosting.',
        'https://www.foodnetwork.com/recipes/ina-garten/vanilla-cupcakes-recipe-1914229', 3.50, 'DESSER', 50, 1),
       ('Cheesecake', 'A rich, creamy cheesecake topped with fresh fruit.',
        'https://www.tasteofhome.com/recipes/new-york-cheesecake/', 6.00, 'DESSER', 100, 1),
       ('Ice Cream Sandwich', 'A chocolate chip cookie with a scoop of vanilla ice cream in the middle.',
        'https://www.foodnetwork.com/recipes/alton-brown/ice-cream-sandwiches-recipe-2124529', 4.00, 'DESSER', 75, 1);